[build]
functions = "src"
  external_node_modules = ["express", "happy-dom"]

  [functions]
  node_bundler = "esbuild"


[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/main/:splat"


[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*" 

# see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin